dataset:
  noisy_test_dataset_dir: /raid/R12K41024/LBCCN/Dataset/noisy_testset/snr_0dB
  noisy_training_dataset_dir: /raid/R12K41024/LBCCN/Dataset/noisy_trainset
  noisy_validation_dataset_dir: /raid/R12K41024/LBCCN/Dataset/noisy_valset
  target_test_dataset_dir: /raid/R12K41024/LBCCN/Dataset/clean_testset
  target_training_dataset_dir: /raid/R12K41024/LBCCN/Dataset/clean_trainset
  target_validation_dataset_dir: /raid/R12K41024/LBCCN/Dataset/clean_valset
defaults:
- model
- training
- dataset: speech_dataset


# 評估階段用的 checkpoint（正式 train 完再填）
eval:
  ckpt_path: null
