# 資料路徑（示意，請自行改成真實路徑）
dataset:
  clean_dir: /path/to/clean
  noise_dir: /path/to/noise
  rir_dir:   /path/to/CIPIC

defaults:
  - model
  - training

model: ${model}

# 評估階段用的 checkpoint（正式 train 完再填）
eval:
  ckpt_path: null
