dataset:
  noisy_test_dataset_dir: /raid/R12K41024/BCCTN/Dataset/noisy_testset/snr_0dB
  noisy_training_dataset_dir: /raid/R12K41024/BCCTN/Dataset/noisy_trainset
  noisy_validation_dataset_dir: /raid/R12K41024/BCCTN/Dataset/noisy_valset
  target_test_dataset_dir: /raid/R12K41024/BCCTN/Dataset/clean_testset
  target_training_dataset_dir: /raid/R12K41024/BCCTN/Dataset/clean_trainset
  target_validation_dataset_dir: /raid/R12K41024/BCCTN/Dataset/clean_valset
defaults:
- model
- training
- dataset: speech_dataset
training:
  accelerator: auto
  batch_size: 32
  learning_rate: 3e-4  # Initial learning rate as per paper
  learning_rate_decay_steps: [3, 8]
  learning_rate_decay_values: 0.5
  n_epochs: 100         # Number of epochs as per paper
  n_workers: 4
  pin_memory: true
  strategy: auto
  train_checkpoint_path: null
  logger: true
  early_stopping:
    enabled: true
    key_to_monitor: validation_loss
    min_delta: 0.01
    patience_in_epochs: 3  # Early stopping after 3 epochs of no improvement