training:
  # --- Training schedule ---
  batch_size:          16      # LBCCN paper 建議輕量 batch :contentReference[oaicite:24]{index=24}:contentReference[oaicite:25]{index=25}
  n_epochs:            50      # 20–50 epochs :contentReference[oaicite:26]{index=26}:contentReference[oaicite:27]{index=27}
  learning_rate:       0.0001  # Adam 初始 LR :contentReference[oaicite:28]{index=28}:contentReference[oaicite:29]{index=29}

  # --- DataLoader & Accelerator ---
  n_workers:           4
  pin_memory:          true
  accelerator:         auto
  strategy:            auto

  # （可選）不用 early stopping，就拿滿 50 epochs
  # early_stopping:
  #   enabled: false
